### ISSUE TITLE
Implement heat loss calculation functions

### ISSUE THREAD

**Issue by Klus3kk** [Klus3kk/temperature_regulator#2]
**Description:**  
Create functions in `simulation.py` to calculate heat losses:

- **Heat loss through glass:**  
```math
Q_{\text{loss-glass}}(t) = k_g \cdot (T(t) - T_{\text{amb}})
```

- **Heat loss through walls:**  
```math
Q_{\text{loss-walls}}(t) = k_w \cdot (T(t) - T_{\text{amb}})
```

- **Total heat loss:**  
```math
Q_{\text{loss}}(t) = Q_{\text{loss-glass}} + Q_{\text{loss-walls}}
```

These functions should take the following parameters:
- \( T(t) \): current temperature,
- \( T_{\text{amb}} \): ambient temperature,
- \( k_g \): heat transfer coefficient for glass,
- \( k_w \): heat transfer coefficient for walls.

**Tasks:**
- [ ] Implement `calculate_heat_loss_glass`.
- [ ] Implement `calculate_heat_loss_walls`.
- [ ] Implement `calculate_total_heat_loss`.
